PB: 30
VB: 28

deep_model:
  # models configurations
  chosen: "linear"
  linear:
    layers_sizes: [16, 16]
    activation: "relu"
  
  optimizer: "adam"

  # training realted parameters
  batch_size: 32
  loader_num_workers: 4
  validate_each_epoch: 500
  print_each: 100
  n_epoch: 5